# Generated by Django 2.2.18 on 2021-03-22 19:33

import datetime

from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ("authnapp", "0007_auto_20210322_1933"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shopuser",
            name="activation_key_expires",
            field=models.DateTimeField(
                default=datetime.datetime(2021, 3, 24, 19, 33, 59, 623227, tzinfo=utc),
                verbose_name="актуальность ключа",
            ),
        ),
    ]
